package Puzzle;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class Puzzle extends javax.swing.JFrame implements ActionListener{
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    /**
     * Creates new form NewJFrame1
     */
    public Puzzle() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane();

        jButton2.setBackground(new java.awt.Color(202, 41, 57));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 102));
        jButton2.setText("Puzzle 2");
        jButton2.setBorder(null);
        jButton2.addActionListener(this);

        getContentPane().add(jButton2);
        jButton2.setBounds(140, 240, 250, 80);

        jButton5.setBackground(new java.awt.Color(202, 41, 57));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 102));
        jButton5.setText("Puzzle 3");
        jButton5.setBorder(null);
        getContentPane().add(jButton5);
        jButton5.setBounds(140, 360, 250, 80);
        jButton5.addActionListener(this);

        jButton6.setBackground(new java.awt.Color(202, 41, 57));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 102));
        jButton6.setText("Puzzle 4");
        jButton6.setBorder(null);
        getContentPane().add(jButton6);
        jButton6.setBounds(140, 480, 250, 80);
        jButton6.addActionListener(this);

        jButton7.setBackground(new java.awt.Color(202, 41, 57));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 102));
        jButton7.setText("Puzzle 1");
        jButton7.setBorder(null);
        getContentPane().add(jButton7);
        jButton7.setBounds(140, 130, 250, 80);
        jButton7.addActionListener(this);

        jLabel1.setIcon(new javax.swing.ImageIcon("src/Resource/PuzzleModeV4.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-3, -4, 540, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == jButton2){
            this.dispose();
            new Puzzle1_GUIs();
        }
        else if (e.getSource() == jButton5){
            this.dispose();
            new Puzzle2_GUIs();
        }
        else if (e.getSource() == jButton6){
            this.dispose();
            new Puzzle3_GUIs();
        }
        else if (e.getSource() == jButton7){
            this.dispose();
            new Puzzle4_GUIs();
        }
    }// </editor-fold> 
}